//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque_Pessoal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelosContainer : DbContext
    {
        public ModelosContainer()
            : base("name=ModelosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> ClienteSet { get; set; }
        public virtual DbSet<Estoque> EstoqueSet { get; set; }
        public virtual DbSet<EstoqueItem> EstoqueItemSet { get; set; }
        public virtual DbSet<Item> ItemSet { get; set; }
    }
}
